language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: goYEBINy/NIjB4L3MEdo8c6e5AJe5neOTHlRc7P5xpip0qHxw34NAKHSnWm2L5rXuyaOwdG/Hl3m/2Qe1I3drGyuA+x8rSd2btq4KU4NV9flpQFPfFPVJjw3Q+axEv0T58tKuQgWVx1mSBKd6PLEBfrWu1WrlQHP+z+sZ5VO5z+TDpuCZNTxp2F/Vau3aMHgTVJXmwMO7UfqZSMlKviYC4Ke1ziYzeP7T5/6eHiJWnY/9Zi0LbiUpSH4KY5sPiT2sMCwRsCm8e2cJ0T4sO6udO7qGnp6LyOKJe8UA7NJ6ig6ZzyhAUOJl/w8oqbK71ZENHkDvG5hLL9ZV5ygL82KZgwxx4ihbHUHvM2QUQeHPWaNFqMFZT38rht4OS2j61jLkEZRlGlT6T8lQi2ODVVxP5j5B7Ddf9lH2ZGeReUjvxM+VhD2WdcpN9ucsHq3Ey9tlzqz8FqMh115Erkwgru7cpEPalJPOSB3CEYjJwULLeCq+wfl5tJHH0DlAjYi0huDmRY3mqstENiDab1UdXV+LjSGGxt1jNuKSjQcmyYgFOcEmHFweO0xI+r8wKvGtxxOCHe5BCkL3j7ofE4IIn+L7p2G/qQytszZ/BVrP4nKfx5z+XyS2pt2AVp23adJvGObwAOoLPteNOwTwndhntaliJN9cIHcrUbjjoyZJnzPzw8=
