title: Zeta Alliance Documentation Repository
description: A community driven repository for Zimbra articles, tips and tricks.
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
url: https://zimbra-community.github.io/jekyll-asciidoc-quickstart
